name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g., 0.2.0) or bump type (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Install LDAP deps
        run: |
          sudo apt-get update
          sudo apt install -y libldap2-dev libsasl2-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Update version
        run: |
          # If the input is a bump type, uv handles it automatically. If not, it sets the specific version
          uv version ${{ github.event.inputs.version }}
          NEW_VERSION=$(grep "^version =" pyproject.toml | cut -d '"' -f 2)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and Tag Release
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml uv.lock
          git commit -m "Release v${{ env.NEW_VERSION }}"
          git tag -a "v${{ env.NEW_VERSION }}" -m "Version ${{ env.NEW_VERSION }}"
          git push origin main --tags

      - name: Build Distributions
        run: uv build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release v${{ env.NEW_VERSION }}
          # Include all files generated in the dist/ directory
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Publish to PyPI
      #  run: uv publish
      #  env:
      #    # Use Trusted Publishing or a manual token
      #    UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}